[package]
name = "codex-account-manager"
version = "0.1.0"
description = "Codex 账号管理器"
authors = ["skywang"]
edition = "2021"

[build]
beforeDevCommand = "npm run vite"
beforeBuildCommand = "vite build"
devUrl = "http://localhost:1420"
frontendDist = "../dist"

[app]
withGlobalTauri = false
windows = [
    {
        title = "Codex 账号管理器",
        width = 1200,
        height = 800,
        resizable = true,
        fullscreen = false
    }
]
security = { csp = null }

[bundle]
identifier = "com.codex.account-manager"
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico"
]
active = true
targets = "all"
