name: Python Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Check Python scripts syntax
      run: |
        python -m py_compile codex_account_manager.py
        python -m py_compile codex_account_manager_web.py
        python -m py_compile switch_account.py
        python -m py_compile backup_current_account.py
        python -m py_compile check_usage.py
        python -m py_compile usage_checker.py
        python -m py_compile config_utils.py

    - name: Test script help commands
      run: |
        python switch_account.py --help || true
        python check_usage.py --help || true
