name: Build Tauri App

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: codex-tauri-app
    env:
      TAURI_CONFIG: ${{ github.workspace }}/codex-tauri-app/src-tauri/tauri.conf.json
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Install NSIS (Windows only)
        if: matrix.platform == 'windows-latest'
        run: choco install nsis -y

      - name: Install frontend dependencies
        run: |
          npm install

      - name: Debug project layout
        run: |
          pwd
          ls -la
          ls -la src-tauri || true

      - name: Build Tauri app via CLI (explicit config)
        run: |
          npm exec tauri -- --version
          npm exec tauri -- build --ci

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-${{ matrix.platform }}
          path: |
            codex-tauri-app/src-tauri/target/release/bundle/
